<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo1.css"?>
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, autor, año, genero?, reseña?)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT genero (#PCDATA)>
    <!ELEMENT reseña (#PCDATA | enfasis)*>
    <!ELEMENT enfasis (#PCDATA)>
]>
<biblioteca>
    <libro>
        <titulo>XML Avanzado</titulo>
        <autor>Juan Pérez</autor>
        <año>2021</año>
        <genero>Tecnología</genero>
    </libro>
    <libro>
        <titulo>Introducción a XML</titulo>
        <autor>María López</autor>
        <año>2019</año>
        <reseña>Este es un <enfasis>excelente</enfasis> libro para empezar.</reseña>
    </libro>
</biblioteca>