=== miGUITel/LM/04/ejemplos/valores2.dtd
<!ELEMENT valores (accion+)> 
<!ELEMENT accion (mercado, nombre, mercado-abierto, fecha)> 
<!ATTLIST accion recomendacion (Comprar | Mantener | Vender) #REQUIRED>
<!ELEMENT mercado (#PCDATA)> 
<!ELEMENT nombre (#PCDATA)> 
<!ELEMENT mercado-abierto (#PCDATA)> 
<!ELEMENT fecha (día, mes, año)> 
<!ELEMENT día (#PCDATA)> 
<!ELEMENT mes (#PCDATA)> 
<!ELEMENT año (#PCDATA)>

=== miGUITel/LM/04/ejemplos/valores2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE valores SYSTEM "valores2.dtd">
<valores>
	<accion recomendacion="Mantener">
		<mercado>Madrid</mercado>
		<nombre>Aceralia</nombre>
		<mercado-abierto>SÍ</mercado-abierto>
		<fecha>
			<día>12</día>
			<mes>07</mes>
			<año>2002</año>
		</fecha>
	</accion>
	<accion recomendacion="Mantener">
		<mercado>Madrid</mercado>
		<nombre>Repsol</nombre>
		<mercado-abierto>SÍ</mercado-abierto>
		<fecha>
			<día>12</día>
			<mes>07</mes>
			<año>2002</año>
		</fecha>
	</accion>
	<accion recomendacion="Comprar">
		<mercado>Barcelona</mercado>
		<nombre>Endesa</nombre>
		<mercado-abierto>No</mercado-abierto>
		<fecha>
			<día>15</día>
			<mes>08</mes>
			<año>2005</año>
		</fecha>
	</accion>
	<accion recomendacion="Vender">
		<mercado>Bilbao</mercado>
		<nombre>Telefónica</nombre>
		<mercado-abierto>SÍ</mercado-abierto>
		<fecha>
			<día>10</día>
			<mes>01</mes>
			<año>2010</año>
		</fecha>
	</accion>
	<accion recomendacion="Mantener">
		<mercado>Madrid</mercado>
		<nombre>Iberdrola</nombre>
		<mercado-abierto>SÍ</mercado-abierto>
		<fecha>
			<día>05</día>
			<mes>06</mes>
			<año>2018</año>
		</fecha>
	</accion>
</valores>
